//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace BLL.Smrz {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SmrzServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SmrzService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetKeyLoginStrOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKeyLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetZSByZSBHOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetZSBySFZHOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOrUpdateRykslOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SmrzService() {
            this.Url = global::BLL.Properties.Settings.Default.BLL_Smrz_SmrzService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetKeyLoginStrCompletedEventHandler GetKeyLoginStrCompleted;
        
        /// <remarks/>
        public event GetKeyLoginCompletedEventHandler GetKeyLoginCompleted;
        
        /// <remarks/>
        public event GetZSByZSBHCompletedEventHandler GetZSByZSBHCompleted;
        
        /// <remarks/>
        public event GetZSBySFZHCompletedEventHandler GetZSBySFZHCompleted;
        
        /// <remarks/>
        public event AddOrUpdateRykslCompletedEventHandler AddOrUpdateRykslCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetKeyLoginStr", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetKeyLoginStr(string keyJm, string userName, string pwdJm) {
            object[] results = this.Invoke("GetKeyLoginStr", new object[] {
                        keyJm,
                        userName,
                        pwdJm});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetKeyLoginStrAsync(string keyJm, string userName, string pwdJm) {
            this.GetKeyLoginStrAsync(keyJm, userName, pwdJm, null);
        }
        
        /// <remarks/>
        public void GetKeyLoginStrAsync(string keyJm, string userName, string pwdJm, object userState) {
            if ((this.GetKeyLoginStrOperationCompleted == null)) {
                this.GetKeyLoginStrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKeyLoginStrOperationCompleted);
            }
            this.InvokeAsync("GetKeyLoginStr", new object[] {
                        keyJm,
                        userName,
                        pwdJm}, this.GetKeyLoginStrOperationCompleted, userState);
        }
        
        private void OnGetKeyLoginStrOperationCompleted(object arg) {
            if ((this.GetKeyLoginStrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKeyLoginStrCompleted(this, new GetKeyLoginStrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetKeyLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetKeyLogin(string keyJm, string zzjgdm, string userName, string pwdJm) {
            object[] results = this.Invoke("GetKeyLogin", new object[] {
                        keyJm,
                        zzjgdm,
                        userName,
                        pwdJm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetKeyLoginAsync(string keyJm, string zzjgdm, string userName, string pwdJm) {
            this.GetKeyLoginAsync(keyJm, zzjgdm, userName, pwdJm, null);
        }
        
        /// <remarks/>
        public void GetKeyLoginAsync(string keyJm, string zzjgdm, string userName, string pwdJm, object userState) {
            if ((this.GetKeyLoginOperationCompleted == null)) {
                this.GetKeyLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKeyLoginOperationCompleted);
            }
            this.InvokeAsync("GetKeyLogin", new object[] {
                        keyJm,
                        zzjgdm,
                        userName,
                        pwdJm}, this.GetKeyLoginOperationCompleted, userState);
        }
        
        private void OnGetKeyLoginOperationCompleted(object arg) {
            if ((this.GetKeyLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKeyLoginCompleted(this, new GetKeyLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetZSByZSBH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetZSByZSBH(string StrZSBH, string userName, string pwdJm) {
            object[] results = this.Invoke("GetZSByZSBH", new object[] {
                        StrZSBH,
                        userName,
                        pwdJm});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetZSByZSBHAsync(string StrZSBH, string userName, string pwdJm) {
            this.GetZSByZSBHAsync(StrZSBH, userName, pwdJm, null);
        }
        
        /// <remarks/>
        public void GetZSByZSBHAsync(string StrZSBH, string userName, string pwdJm, object userState) {
            if ((this.GetZSByZSBHOperationCompleted == null)) {
                this.GetZSByZSBHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetZSByZSBHOperationCompleted);
            }
            this.InvokeAsync("GetZSByZSBH", new object[] {
                        StrZSBH,
                        userName,
                        pwdJm}, this.GetZSByZSBHOperationCompleted, userState);
        }
        
        private void OnGetZSByZSBHOperationCompleted(object arg) {
            if ((this.GetZSByZSBHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetZSByZSBHCompleted(this, new GetZSByZSBHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetZSBySFZH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetZSBySFZH(string StrSFZH, string userName, string pwdJm) {
            object[] results = this.Invoke("GetZSBySFZH", new object[] {
                        StrSFZH,
                        userName,
                        pwdJm});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetZSBySFZHAsync(string StrSFZH, string userName, string pwdJm) {
            this.GetZSBySFZHAsync(StrSFZH, userName, pwdJm, null);
        }
        
        /// <remarks/>
        public void GetZSBySFZHAsync(string StrSFZH, string userName, string pwdJm, object userState) {
            if ((this.GetZSBySFZHOperationCompleted == null)) {
                this.GetZSBySFZHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetZSBySFZHOperationCompleted);
            }
            this.InvokeAsync("GetZSBySFZH", new object[] {
                        StrSFZH,
                        userName,
                        pwdJm}, this.GetZSBySFZHOperationCompleted, userState);
        }
        
        private void OnGetZSBySFZHOperationCompleted(object arg) {
            if ((this.GetZSBySFZHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetZSBySFZHCompleted(this, new GetZSBySFZHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOrUpdateRyksl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddOrUpdateRyksl(RyxxModel model, string userName, string pwdJm) {
            object[] results = this.Invoke("AddOrUpdateRyksl", new object[] {
                        model,
                        userName,
                        pwdJm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddOrUpdateRykslAsync(RyxxModel model, string userName, string pwdJm) {
            this.AddOrUpdateRykslAsync(model, userName, pwdJm, null);
        }
        
        /// <remarks/>
        public void AddOrUpdateRykslAsync(RyxxModel model, string userName, string pwdJm, object userState) {
            if ((this.AddOrUpdateRykslOperationCompleted == null)) {
                this.AddOrUpdateRykslOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOrUpdateRykslOperationCompleted);
            }
            this.InvokeAsync("AddOrUpdateRyksl", new object[] {
                        model,
                        userName,
                        pwdJm}, this.AddOrUpdateRykslOperationCompleted, userState);
        }
        
        private void OnAddOrUpdateRykslOperationCompleted(object arg) {
            if ((this.AddOrUpdateRykslCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOrUpdateRykslCompleted(this, new AddOrUpdateRykslCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RyxxModel {
        
        private string xmField;
        
        private string xbField;
        
        private string mzField;
        
        private System.Nullable<System.DateTime> cSRQField;
        
        private string jTDZField;
        
        private string sFZHField;
        
        private string fZJGField;
        
        private System.Nullable<System.DateTime> sFZYXKSRQField;
        
        private System.Nullable<System.DateTime> sFZYXJZRQField;
        
        private string sBHField;
        
        private byte[] zpField;
        
        private string sJHMField;
        
        private string qYMCField;
        
        private string zZJGDMField;
        
        private string zwField;
        
        private string zcField;
        
        private string zSLXField;
        
        private string zSBHField;
        
        private string zSBMField;
        
        private System.Nullable<System.DateTime> fZRQField;
        
        private System.Nullable<System.DateTime> zSYXJZRQField;
        
        private string sTATEField;
        
        private string zSMCField;
        
        private System.Nullable<System.DateTime> zSSCSJField;
        
        /// <remarks/>
        public string XM {
            get {
                return this.xmField;
            }
            set {
                this.xmField = value;
            }
        }
        
        /// <remarks/>
        public string XB {
            get {
                return this.xbField;
            }
            set {
                this.xbField = value;
            }
        }
        
        /// <remarks/>
        public string MZ {
            get {
                return this.mzField;
            }
            set {
                this.mzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CSRQ {
            get {
                return this.cSRQField;
            }
            set {
                this.cSRQField = value;
            }
        }
        
        /// <remarks/>
        public string JTDZ {
            get {
                return this.jTDZField;
            }
            set {
                this.jTDZField = value;
            }
        }
        
        /// <remarks/>
        public string SFZH {
            get {
                return this.sFZHField;
            }
            set {
                this.sFZHField = value;
            }
        }
        
        /// <remarks/>
        public string FZJG {
            get {
                return this.fZJGField;
            }
            set {
                this.fZJGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SFZYXKSRQ {
            get {
                return this.sFZYXKSRQField;
            }
            set {
                this.sFZYXKSRQField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SFZYXJZRQ {
            get {
                return this.sFZYXJZRQField;
            }
            set {
                this.sFZYXJZRQField = value;
            }
        }
        
        /// <remarks/>
        public string SBH {
            get {
                return this.sBHField;
            }
            set {
                this.sBHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ZP {
            get {
                return this.zpField;
            }
            set {
                this.zpField = value;
            }
        }
        
        /// <remarks/>
        public string SJHM {
            get {
                return this.sJHMField;
            }
            set {
                this.sJHMField = value;
            }
        }
        
        /// <remarks/>
        public string QYMC {
            get {
                return this.qYMCField;
            }
            set {
                this.qYMCField = value;
            }
        }
        
        /// <remarks/>
        public string ZZJGDM {
            get {
                return this.zZJGDMField;
            }
            set {
                this.zZJGDMField = value;
            }
        }
        
        /// <remarks/>
        public string ZW {
            get {
                return this.zwField;
            }
            set {
                this.zwField = value;
            }
        }
        
        /// <remarks/>
        public string ZC {
            get {
                return this.zcField;
            }
            set {
                this.zcField = value;
            }
        }
        
        /// <remarks/>
        public string ZSLX {
            get {
                return this.zSLXField;
            }
            set {
                this.zSLXField = value;
            }
        }
        
        /// <remarks/>
        public string ZSBH {
            get {
                return this.zSBHField;
            }
            set {
                this.zSBHField = value;
            }
        }
        
        /// <remarks/>
        public string ZSBM {
            get {
                return this.zSBMField;
            }
            set {
                this.zSBMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FZRQ {
            get {
                return this.fZRQField;
            }
            set {
                this.fZRQField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ZSYXJZRQ {
            get {
                return this.zSYXJZRQField;
            }
            set {
                this.zSYXJZRQField = value;
            }
        }
        
        /// <remarks/>
        public string STATE {
            get {
                return this.sTATEField;
            }
            set {
                this.sTATEField = value;
            }
        }
        
        /// <remarks/>
        public string ZSMC {
            get {
                return this.zSMCField;
            }
            set {
                this.zSMCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ZSSCSJ {
            get {
                return this.zSSCSJField;
            }
            set {
                this.zSSCSJField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetKeyLoginStrCompletedEventHandler(object sender, GetKeyLoginStrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKeyLoginStrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKeyLoginStrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetKeyLoginCompletedEventHandler(object sender, GetKeyLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKeyLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKeyLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetZSByZSBHCompletedEventHandler(object sender, GetZSByZSBHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetZSByZSBHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetZSByZSBHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetZSBySFZHCompletedEventHandler(object sender, GetZSBySFZHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetZSBySFZHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetZSBySFZHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void AddOrUpdateRykslCompletedEventHandler(object sender, AddOrUpdateRykslCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOrUpdateRykslCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOrUpdateRykslCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591